/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{373:function(ha,ca,f){function aa(e){e.La();e.advance();var h=e.current.textContent;e.Za();return h}function x(e){var h=[];for(e.La();e.advance();){var f=e.Oa();"field"===f?h.push(String(e.da("name"))):Object(ea.i)("unrecognised field list element: "+f)}e.Za();return h}function fa(e,h){return h?"false"!==e:"true"===e}function da(e,h){var f=e.Oa();switch(f){case "javascript":return{name:"JavaScript",javascript:e.current.textContent};
case "uri":return{name:"URI",uri:e.da("uri")};case "goto":f=null;e.La();if(e.advance()){var n=e.da("fit");f={page:e.da("page"),fit:n};if("0"===f.page)Object(ea.i)("null page encountered in dest");else switch(h=h(Number(f.page)),n){case "Fit":case "FitB":break;case "FitH":case "FitBH":f.top=h.qa({x:0,y:e.da("top")||0}).y;break;case "FitV":case "FitBV":f.left=h.qa({x:e.da("left")||0,y:0}).x;break;case "FitR":n=h.qa({x:e.da("left")||0,y:e.da("top")||0});h=h.qa({x:e.da("right")||0,y:e.da("bottom")||0});
h=new va.d(n.x,n.y,h.x,h.y);f.top=h.ha;f.left=h.ka;f.bottom=h.ia;f.right=h.la;break;case "XYZ":n=h.qa({x:e.da("left")||0,y:e.da("top")||0});f.top=n.y;f.left=n.x;f.zoom=e.da("zoom")||0;break;default:Object(ea.i)("unknown dest fit: "+n)}f={name:"GoTo",dest:f}}else Object(ea.i)("missing dest in GoTo action");e.Za();return f;case "submit-form":f={name:"SubmitForm",url:e.da("url"),format:e.da("format"),method:e.da("method")||"POST",exclude:fa(e.da("exclude"),!1)};h=e.da("flags");f.flags=h?h.split(" "):
[];for(e.La();e.advance();)switch(h=e.Oa(),h){case "fields":f.fields=x(e);break;default:Object(ea.i)("unrecognised submit-form child: "+h)}e.Za();return f;case "reset-form":f={name:"ResetForm",exclude:fa(e.da("exclude"),!1)};for(e.La();e.advance();)switch(h=e.Oa(),h){case "fields":f.fields=x(e);break;default:Object(ea.i)("unrecognised reset-form child: "+h)}e.Za();return f;case "hide":f={name:"Hide",hide:fa(e.da("hide"),!0)};for(e.La();e.advance();)switch(h=e.Oa(),h){case "fields":f.fields=x(e);break;
default:Object(ea.i)("unrecognised hide child: "+h)}e.Za();return f;case "named":return{name:"Named",action:e.da("name")};default:Object(ea.i)("Encountered unexpected action type: "+f)}return null}function ba(e,h,f){var n={};for(e.La();e.advance();){var r=e.Oa();switch(r){case "action":r=e.da("trigger");if(h?-1!==h.indexOf(r):1){n[r]=[];for(e.La();e.advance();){var w=da(e,f);Object(pa.isNull)(w)||n[r].push(w)}e.Za()}else Object(ea.i)("encountered unexpected trigger on field: "+r);break;default:Object(ea.i)("encountered unknown action child: "+
r)}}e.Za();return n}function y(e){return new la.a(e.da("r")||0,e.da("g")||0,e.da("b")||0,e.da("a")||1)}function r(e,h){var f=e.da("name"),n=e.da("type")||"Type1",r=e.da("size"),w=h.qa({x:0,y:0});r=h.qa({x:Number(r),y:0});h=w.x-r.x;w=w.y-r.y;f={name:f,type:n,size:Math.sqrt(h*h+w*w)||0,strokeColor:[0,0,0],fillColor:[0,0,0]};for(e.La();e.advance();)switch(n=e.Oa(),n){case "stroke-color":f.strokeColor=y(e);break;case "fill-color":f.fillColor=y(e);break;default:Object(ea.i)("unrecognised font child: "+
n)}e.Za();return f}function n(e){return{value:e.da("value"),displayValue:e.da("display-value")||void 0}}function h(e){var h=[];for(e.La();e.advance();){var f=e.Oa();switch(f){case "option":h.push(n(e));break;default:Object(ea.i)("unrecognised options child: "+f)}}e.Za();return h}function e(e,f){var n=e.da("name"),w={type:e.da("type"),quadding:e.da("quadding")||"Left-justified",maxLen:e.da("max-len")||-1},x=e.da("flags");Object(pa.isString)(x)&&(w.flags=x.split(" "));for(e.La();e.advance();)switch(x=
e.Oa(),x){case "actions":w.actions=ba(e,["C","F","K","V"],function(){return f});break;case "default-value":w.defaultValue=aa(e);break;case "font":w.font=r(e,f);break;case "options":w.options=h(e);break;default:Object(ea.i)("unknown field child: "+x)}e.Za();return new window.Annotations.fa.ra(n,w)}function w(e,h){switch(e.type){case "Tx":try{if(Object(ra.c)(e.actions))return new ka.a.DatePickerWidgetAnnotation(e,h)}catch(qa){Object(ea.i)(qa)}return new ka.a.TextWidgetAnnotation(e,h);case "Ch":return e.flags.get(oa.WidgetFlags.COMBO)?
new ka.a.ChoiceWidgetAnnotation(e,h):new ka.a.ListWidgetAnnotation(e,h);case "Btn":return e.flags.get(oa.WidgetFlags.PUSH_BUTTON)?new ka.a.PushButtonWidgetAnnotation(e,h):e.flags.get(oa.WidgetFlags.RADIO)?new ka.a.RadioButtonWidgetAnnotation(e,h):new ka.a.CheckButtonWidgetAnnotation(e,h);case "Sig":return new ka.a.SignatureWidgetAnnotation(e,h);default:Object(ea.i)("Unrecognised field type: "+e.type)}return null}function z(e,h){var f={number:e.da("number")};for(e.La();e.advance();){var n=e.Oa();switch(n){case "actions":f.actions=
ba(e,["O","C"],h);break;default:Object(ea.i)("unrecognised page child: "+n)}}e.Za();return f}function ia(h,f,n,aa){var da=[],ca={};h.La();var fa=[],ia={},ha=[];Object(ja.a)(function(){if(h.advance()){var n=h.Oa();switch(n){case "calculation-order":fa="calculation-order"===h.Oa()?x(h):[];break;case "document-actions":ia=ba(h,["Init","Open"],f);break;case "pages":n=[];for(h.La();h.advance();){var aa=h.Oa();switch(aa){case "page":n.push(z(h,f));break;default:Object(ea.i)("unrecognised page child: "+
aa)}}h.Za();ha=n;break;case "field":aa=e(h,f(1));ca[aa.name]=aa;break;case "widget":n={border:{style:"Solid",width:1},backgroundColor:[],fieldName:h.da("field"),page:h.da("page"),index:h.da("index")||0,rotation:h.da("rotation")||0,flags:[],isImporting:!0};(aa=h.da("appearance"))&&(n.appearance=aa);(aa=h.da("flags"))&&(n.flags=aa.split(" "));for(h.La();h.advance();)switch(aa=h.Oa(),aa){case "rect":var ka=h,ja=f(Number(n.page));aa=ja.qa({x:ka.da("x1")||0,y:ka.da("y1")||0});ka=ja.qa({x:ka.da("x2")||
0,y:ka.da("y2")||0});aa=new va.d(aa.x,aa.y,ka.x,ka.y);aa.normalize();n.rect={x1:aa.x1,y1:aa.y1,x2:aa.x2,y2:aa.y2};break;case "border":aa=h;ka={style:aa.da("style")||"Solid",width:aa.da("width")||1,color:[0,0,0]};for(aa.La();aa.advance();)switch(ja=aa.Oa(),ja){case "color":ka.color=y(aa);break;default:Object(ea.i)("unrecognised border child: "+ja)}aa.Za();n.border=ka;break;case "background-color":n.backgroundColor=y(h);break;case "actions":n.actions=ba(h,"E X D U Fo Bl PO PC PV PI".split(" "),f);break;
case "appearances":aa=h;ka=Object(ra.b)(n,"appearances");for(aa.La();aa.advance();)if(ja=aa.Oa(),"appearance"===ja){ja=aa.da("name");var qa=Object(ra.b)(ka,ja);ja=aa;for(ja.La();ja.advance();){var na=ja.Oa();switch(na){case "Normal":Object(ra.b)(qa,"Normal").data=ja.current.textContent;break;default:Object(ea.i)("unexpected appearance state: ",na)}}ja.Za()}else Object(ea.i)("unexpected appearances child: "+ja);aa.Za();break;case "extra":aa=h;ka=f;ja={};for(aa.La();aa.advance();)switch(qa=aa.Oa(),
qa){case "font":ja.font=r(aa,ka(1));break;default:Object(ea.i)("unrecognised extra child: "+qa)}aa.Za();aa=ja;aa.font&&(n.font=aa.font);break;case "captions":ka=h;aa={};(ja=ka.da("Normal"))&&(aa.Normal=ja);(ja=ka.da("Rollover"))&&(aa.Rollover=ja);(ka=ka.da("Down"))&&(aa.Down=ka);n.captions=aa;break;default:Object(ea.i)("unrecognised widget child: "+aa)}h.Za();(aa=ca[n.fieldName])?(n=w(aa,n),da.push(n)):Object(ea.i)("ignoring widget with no corresponding field data: "+n.fieldName);break;default:Object(ea.i)("Unknown element encountered in PDFInfo: "+
n)}return!0}return!1},function(){h.Za();n({calculationOrder:fa,widgets:da,fields:ca,documentActions:ia,pages:ha,custom:[]})},aa)}f.r(ca);f.d(ca,"parse",function(){return ia});var ea=f(1),pa=f(0);f.n(pa);var ka=f(101),va=f(2),la=f(7),ja=f(27),ra=f(86),oa=f(13)}}]);}).call(this || window)
