/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[13],{367:function(ha,ca,f){f.r(ca);var aa=f(4),x=f(0);f.n(x);var fa=f(1),da=f(124);ha=f(43);var ba=f(79),y=f(201),r=f(56),n=f(200);f=f(312);var h=window,e=function(){function e(e,h,f){var w=-1===e.indexOf("?")?"?":"&";switch(h){case r.a.NEVER_CACHE:this.url=e+w+"_="+Object(x.uniqueId)();break;default:this.url=e}this.pf=f;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=n.a.NOT_STARTED}e.prototype.start=function(h,f){var r=this,w=this,x=this.request,y;w.ev=0;h&&Object.keys(h).forEach(function(e){r.request.setRequestHeader(e,h[e])});f&&(this.request.withCredentials=f);this.fB=setInterval(function(){var h=0===window.document.URL.indexOf("file:///");h=200===x.status||h&&0===x.status;
if(x.readyState!==n.b.DONE||h){try{x.responseText}catch(oa){return}w.ev<x.responseText.length&&(y=w.t$())&&w.trigger(e.Events.DATA,[y]);0===x.readyState&&(clearInterval(w.fB),w.trigger(e.Events.DONE))}else clearInterval(w.fB),w.trigger(e.Events.DONE,["Error received return status "+x.status])},1E3);this.request.send(null);this.status=n.a.STARTED};e.prototype.t$=function(){var f=this.request,n=f.responseText;if(0!==n.length)if(this.ev===n.length)clearInterval(this.fB),this.trigger(e.Events.DONE);else return n=
Math.min(this.ev+3E6,n.length),f=h.rP(f,this.ev,!0,n),this.ev=n,f};e.prototype.abort=function(){clearInterval(this.fB);var h=this;this.request.onreadystatechange=function(){Object(fa.i)("StreamingRequest aborted");h.status=n.a.ABORTED;return h.trigger(e.Events.ABORTED)};this.request.abort()};e.prototype.finish=function(){var h=this;this.request.onreadystatechange=function(){h.status=n.a.SUCCESS;return h.trigger(e.Events.DONE)};this.request.abort()};e.Events={DONE:"done",DATA:"data",ABORTED:"aborted"};
return e}();Object(ha.a)(e);var w;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(w||(w={}));var z=function(e){function h(){var h=e.call(this)||this;h.buffer="";h.state=w.LOCAL_HEADER;h.fJ=4;h.Zk=null;h.Gr=da.c;h.wm={};return h}Object(aa.c)(h,e);h.prototype.n$=function(e){var f;for(e=this.buffer+e;e.length>=this.Gr;)switch(this.state){case w.LOCAL_HEADER:this.Zk=f=this.x$(e.slice(0,this.Gr));if(f.os!==da.g)throw Error("Wrong signature in local header: "+
f.os);e=e.slice(this.Gr);this.state=w.FILE;this.Gr=f.hE+f.gp+f.lu+this.fJ;this.trigger(h.Events.HEADER,[f]);break;case w.FILE:this.Zk.name=e.slice(0,this.Zk.gp);this.wm[this.Zk.name]=this.Zk;f=this.Gr-this.fJ;var n=e.slice(this.Zk.gp+this.Zk.lu,f);this.trigger(h.Events.FILE,[this.Zk.name,n,this.Zk.yE]);e=e.slice(f);if(e.slice(0,this.fJ)===da.h)this.state=w.LOCAL_HEADER,this.Gr=da.c;else return this.state=w.CENTRAL_DIR,!0}this.buffer=e;return!1};h.Events={HEADER:"header",FILE:"file"};return h}(y.a);
Object(ha.a)(z);ha=function(h){function f(f,n,r,w,x){r=h.call(this,f,r,w)||this;r.url=f;r.stream=new e(f,n);r.Od=new z;r.ZR=window.createPromiseCapability();r.vS={};r.pf=x;return r}Object(aa.c)(f,h);f.prototype.Tv=function(h){var f=this;this.request([this.Ji,this.Vj,this.Ii]);this.stream.addEventListener(e.Events.DATA,function(e){try{if(f.Od.n$(e))return f.stream.finish()}catch(la){throw f.stream.abort(),f.iu(la),h(la),la;}});this.stream.addEventListener(e.Events.DONE,function(e){f.U9=!0;f.ZR.resolve();
e&&(f.iu(e),h(e))});this.Od.addEventListener(z.Events.HEADER,Object(x.bind)(this.uS,this));this.Od.addEventListener(z.Events.FILE,Object(x.bind)(this.N$,this));return this.stream.start(this.pf,this.withCredentials)};f.prototype.oP=function(e){var h=this;this.ZR.promise.then(function(){e(Object.keys(h.Od.wm))})};f.prototype.Zm=function(){return!0};f.prototype.request=function(e){var h=this;this.U9&&e.forEach(function(e){h.vS[e]||h.Sda(e)})};f.prototype.uS=function(){};f.prototype.abort=function(){this.stream&&
this.stream.abort()};f.prototype.Sda=function(e){this.trigger(ba.a.Events.PART_READY,[{ab:e,error:"Requested part not found",Qh:!1,Lf:!1}])};f.prototype.N$=function(e,h,f){this.vS[e]=!0;this.trigger(ba.a.Events.PART_READY,[{ab:e,data:h,Qh:!1,Lf:!1,error:null,cd:f}])};return f}(ba.a);Object(f.a)(ha);Object(f.b)(ha);ca["default"]=ha}}]);}).call(this || window)
